name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup FOSSA
      run: "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash"
    - name: Configure Gradle
      # Initial gradle configuration, install dependencies, etc
      run: ./gradlew help
    - name: Spot check
      # Run spotless first to fail fast on spotless issues
      run: ./gradlew spotlessCheck --stacktrace
    - name: Build project
      run: ./gradlew assemble --stacktrace
    - name: Run tests
      run: ./gradlew test --stacktrace
    - name: Final checks
      run: ./gradlew check --stacktrace
    - name: Init FOSSA
      run: fossa init
    - name: Analyze FOSSA
      run: fossa analyze
      env:
        FOSSA_API_KEY: 10d9d2e111c236cb776e7bb7c09bf244
    - name: Upload snapshot (main only)
      run: ./gradlew uploadArchives --stacktrace --no-daemon --no-parallel
      env:
        SONATYPE_NEXUS_USERNAME: ${{ secrets.SonatypeUsername }}
        SONATYPE_NEXUS_PASSWORD: ${{ secrets.SonatypePassword }}
      if: success() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
