name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Configure Gradle
        # Initial gradle configuration, install dependencies, etc
        run: ./gradlew help

      - name: Spot check
        # Run spotless first to fail fast on spotless issues
        run: ./gradlew spotlessCheck --stacktrace

      - name: Build project
        run: ./gradlew assemble --stacktrace

      - name: Run tests
        run: ./gradlew test --stacktrace

      - name: Final checks
        run: ./gradlew check --stacktrace

      - name: Run FOSSA scan and upload build data
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: 10d9d2e111c236cb776e7bb7c09bf244
          github-token: ${{ github.token }}

      - name: Upload snapshot (main only)
        if: success() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: ./gradlew uploadArchives --stacktrace --no-daemon --no-parallel
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SonatypeUsername }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SonatypePassword }}
